services:
  - type: web
    name: clarity-finance-backend
    runtime: python
    rootDir: backend
    buildCommand: apt-get install -y tesseract-ocr && pip install -r requirements.txt
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py